### PR TITLE
Add export default & modify default params

### PR DESCRIPTION
**Pull request by DenisCarriere**
dependency for `rbush` (PR https://github.com/mourner/rbush/pull/79)

Ref: https://github.com/mapbox/supercluster/pull/62

**Note: Moved default params to the main `quickselect` function

### CODE REVIEW

**Review by mourner — CHANGES_REQUESTED** [review]
@DenisCarriere please see https://github.com/mourner/quickselect/commit/ba9702b883ec5fd05dbce9affd255a69ebab4f60 with the discussion

**Comment by DenisCarriere** [comment]
👍 My bad.. didn't follow that thread 😄 I'll submit a change

**Comment by DenisCarriere** [comment]
@mourner Added `main()` to handle the default params, then `quickselect` executes recursively without calculating the default params.

**Comment by mourner** [comment]
Let's rename `main` to `quickselect `and `quickselect` to `quickselectStep` to keep stack traces nice.

**Comment by DenisCarriere** [comment]
👍 Make sense, didn't know how you wanted to rename that method, but I like it!

**Comment by DenisCarriere** [comment]
Done 🎉

**Comment by mourner** [comment]
@DenisCarriere you forgot to rename the internal `quickselect` call. It doesn't trigger failures but it's a perf hit.

**Comment by DenisCarriere** [comment]
Ops! True 🤦‍♂️

**Comment by DenisCarriere** [comment]
Renamed internal `quickselect`

**Review by mourner — APPROVED** [review]

**Pull request merged**
